### ISSUE TITLE
CRITICAL : Diagnosis not reached: Severe acute malnutrition

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#234]
## Environment
TIMCI Senegal (test facility 149)
Lenovo TB-8505F

## Describe the bug
Should reach Uncomplicated severe acute malnutrition (because MUAC <115mm) - only reach moderately low weight for age

## HYPOTHESIS
Following the related diagrams in medal-c, looks that value of MUAC z-score is not taken into account.
Moreover as moderate malnutriation isn't reach also, looks that wfh z-score is not taken into account also.

## Medical Case Info
Link to diagram: https://liwi-test.wavelab.top/algorithms/7/versions/41/diagnoses/3218/diagram#

### Registration
DoB 09/04/2019

### Complaint Categories
CCs: Fever

### Basic Measurements
Weight 10kg
Height 87cm
MUAC 112 mm
Temp 37.4

### Medial History
No to all danger signs
Fever within the last 2 days : Yes
Duration of fever 3 days
Everything else: No, Absent, Not feasible

### Physical Exams
Everything: No, Absent, Not feasible

### Assessments
Appetite test should appear

**Comment by frescoal** [comment]
Plusieurs problems dans l'algorithme médical

### Problème 1
https://liwi-test.wavelab.top/questions_sequences/9200/diagram ==> Vide
Il est appelé par https://liwi-test.wavelab.top/questions_sequences/8995/diagram#
Qui est appelé par https://liwi-test.wavelab.top/questions_sequences/9201/diagram#
Qui est dans https://liwi-test.wavelab.top/algorithms/7/versions/41/diagnoses/3218/diagram#

### Problème 2
 https://liwi-test.wavelab.top/questions_sequences/8948/diagram
A33 est pas répondu
donc DC3 n'a pas de réponse
Donc PS38 Ne peux pas être à false
Donc PS61 ne peux pas être à false

### Problème 3
https://liwi-test.wavelab.top/questions_sequences/9201/diagram
A34 n'est pas répondu non plus donc PS61 ne peux pas être à false

**Comment by jouz56k** [comment]
gg

**Comment by jouz56k** [comment]
J'ai retesté en faisant les modifications suggéré
Grâce à ça un diagnostique finale a pu être reach -> complicated acute severe malnutrition
On dirait que SAM medical complication est set to Yes, au lieu de No
ce qui explique pourquoi l'Apetite test n'apparait pas,
Ce pendant j'ai fouiné dans SAM medical complication et je n'arrive pas à trouver ce qui la fait set to yes

**Comment by alanvonlanthen** [comment]
Allons-y étape par étape... 
Le test "A17 - Appetite Test" n'est pas demandé dans le scénario suivant : 
Environnement liwi-test
Algo TIMCI Tanzania

Registration
DoB 09/04/2019
Sex: M

Complaint Categories
CCs: Fever

Basic Measurements
Weight 10kg
Height 87cm
MUAC 11.2 cm
Temp 37.4

Medical History
No to all danger signs
Fever within the last 2 days : Yes
Duration of fever 3 days
Everything else: No, Absent, Not feasible

Physical Exams
Everything: No, Absent, Not feasible

Assessments
Appetite test should appear but doesn't. See comments below

![image](https://user-images.githubusercontent.com/2785940/127139119-e57d7216-f866-44a4-98e6-18a47ccdf3d9.png)

DC1 6151 Severe acute malnutrition = YES (because age > 24m && MUAC < 11.5 cm) 
PS61 5469 SAM medical complication = NO (because PS81 = FALSE (because PE136 Generalized skin problem = ABSENT && PS38 Severe diagnosis = FALSE ** && PE159 Oxygen saturation = Not feasible && Blood glucose test = Unavailable) 

** Details of PS38 FALSE (1st level only, but I checked every subalgorithm): 
* PS80 VSD/VSFD: FALSE
* PS4 Resp distress: FALSE
* PS27 Suspicion of foreign obj: FALSE
* PS26 Severe croup: FALSE
* PS29 Severe malaria: FALSE
* PS30 Complicated prol. fever: FALSE
* DC3 Severe anemia: FALSE
* PS33 Mastoiditis: FALSE
* PS28 Severe dehydration: FALSE
* PS32 Severe abdominal cond: FALSE
* PS34 Severe eye disease: FALSE
* PS36 Complicated abscess: FALSE
* PS35 Complicated cellulitis: FALSE
* OS37 Osteomyelitis: FALSE
